<?php

/**
 * Lightweight router to preview static files generated by build-static.php.
 * Run: php -S 127.0.0.1:8000 serve-static.php
 *
 * This serves files from the public/ directory (index.html, sd.html, etc.)
 * and rewrites .php URLs to their .html counterparts so existing links work.
 */

$publicDir = __DIR__ . '/public';

$requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
$requestPath = is_string($requestPath) ? trim($requestPath, '/') : '';

// Rewrite .php requests to .html equivalents in public/
if ($requestPath === '' || $requestPath === 'index.php') {
    $requestPath = 'index.html';
} elseif (preg_match('/\.php$/', $requestPath)) {
    $requestPath = preg_replace('/\.php$/', '.html', $requestPath);
}

$filePath = $publicDir . '/' . $requestPath;

if (is_file($filePath)) {
    $extension = pathinfo($filePath, PATHINFO_EXTENSION);
    $mimeTypes = [
        'html' => 'text/html',
        'css'  => 'text/css',
        'js'   => 'application/javascript',
        'json' => 'application/json',
        'png'  => 'image/png',
        'jpg'  => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'gif'  => 'image/gif',
        'svg'  => 'image/svg+xml',
        'webp' => 'image/webp',
        'ico'  => 'image/x-icon',
        'woff' => 'font/woff',
        'woff2' => 'font/woff2',
    ];

    $mime = $mimeTypes[$extension] ?? 'application/octet-stream';
    header('Content-Type: ' . $mime);
    readfile($filePath);
    return true;
}

http_response_code(404);
?>
<!doctype html>
<html lang="id"><head><meta charset="utf-8"><title>404 - Halaman Tidak Ditemukan</title></head>
<body><main><h1>404 - Halaman Tidak Ditemukan</h1><p>Alamat yang diminta tidak tersedia di build statis.</p><p><a href="/">Kembali ke beranda</a></p></main></body></html>
